name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pygimli>=1.5.3
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - scipy>=1.10.0
  - fastapi>=0.110.0
  - uvicorn>=0.25.0
  - pydantic>=2.0.0
  - python-dotenv>=1.0.0
  - pip
  - pip:
    - motor>=3.3.0
    - pymongo>=4.6.0
